# Ejercicios


```{r}
#| results: "asis"
#| echo: false
source("../_common.R")
```

<!-- ## Ejercicio 1 -->

<!-- Crea un script en el que hagas lo siguiente: -->

<!-- -   Cargar librerías necesarias -->
<!-- -   Importar datos -->
<!-- -   Preparar datos -->
<!-- -   Crear gráfica -->
<!-- -   Crear tabla -->

<!-- Tendrás que mostrar como corre el script con una sesión limpia de RStudio (CONTROL + SHIFT + F10) -->

<!-- #### Notas {.ejercicio .unnumbered} -->

<!-- (importar datos): Los datos deberían ser, idealmente, de un proyecto en el que estés trabajando. Si no tienes datos disponibles, puedes encontrar bases de datos abiertas de varias maneras: -->

<!-- -   Tidytuesday: <https://github.com/rfordatascience/tidytuesday> -->
<!-- -   Buscando en Google Scholar papers que comparten sus datos: <https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=data+available+%22osf.io%22+psychology&btnG=> -->
<!-- -   Buscando directamente en Open Science Foundation: <https://osf.io/> -->

<!-- (preparación de datos): Algunos ejemplos de preparación de datos: renombrar variables, filtrar, computar nuevas variables, combinar bases... -->

<!-- (gráfica): Algunos ejemplos de gráficas: distribución de variable/s, relación entre variables, ... -->

<!-- (tabla): Algunos ejemplos de tablas: promedios por condición, media, mediana, max y min para algunas variables claves... -->

------------------------------------------------------------------------

<!-- ## Ejercicio 2 -->

<!-- Crea la siguiente tarea en jsPsychMaker: -->

<!-- -   [The Brief Resilience Scale](https://sci-hub.ru/10.1080/10705500802222972) (PDF version inglesa), o en su [versión española](https://scielo.isciii.es/scielo.php?script=sci_arttext&pid=S0212-97282021000200006&lng=es&tlng=es) -->

<!-- #### Notas {.ejercicio .unnumbered} -->

<!-- (tareas jsPsychMaker): Ver instrucciones en [experimentos-reproducibles](#experimentos-reproducibles) -->

<!-- Si prefieres puedes implementar una tarea distinta. Los únicos requisitos son que sea breve y sencilla. -->

<!-- ------------------------------------------------------------------------ -->

## Ejercicio 1

Diseña un **sencillo** experimento:

-   Debes usar alguna de las [tareas que aparecen en en manual](https://gorkang.github.io/jsPsychR-manual/qmd/03-jsPsychMaker.html#available-tasks) (máximo 2)
<!-- -   Además, debes diseñar una nueva tarea **muy sencilla** o adaptar una nueva escala -->
-   La duración total del "experimento" no debería superar los 5 minutos

Tendrás que hacer una breve presentación contándonos el diseño experimental.

#### Notas {.ejercicio .unnumbered}

(tareas jsPsychMaker): Usa un máximo de 2 tareas\
<!-- (tarea nueva): Puedes diseñar una tarea con una sola pregunta para dos condiciones experimentales, o adaptar un cuestionario breve ya existente (que no tengamos en jsPsychMaker). -->

------------------------------------------------------------------------

## Ejercicio FINAL

El profesor os ayudará a simular datos para tu experimento con jsPsychMonkeys.

Una vez tengamos los datos:

-   Crearemos un proyecto de jsPsychHelpeR que procesará los datos automáticamente

-   Crearemos un reporte en Rmd como parte del pipeline de jsPsychHelpeR donde incluiremos:

    -   Tabla/s con descriptivos

    -   Gráfico/s con resultado

    -   Tabla/s con resultados de un análisis sencillo

    -   Una frase reportando resultados del análisis (usando [Texto inline de gtsummary](06-analisis-datos-inferencial.html#texto-inline))

El proyecto tiene que correr en cualquier computador.  


### IMPORTANTE {-}

La nota del workshop estará basada en el resultado de esta tarea.  

Tendréis que compartir el proyecto completo con el profesor, y él deberá poder correrlo y ver como resultado el reporte en pdf incluyendo los elementos detallados arriba.  


#### Notas {.ejercicio .unnumbered}

(simulación datos): El profesor os ayudara con esto y/o os compartirá los datos\
(procesamiento datos): Ver [el manual de jsPsychR](https://gorkang.github.io/jsPsychR-manual/qmd/02-QuickGuide.html#QuickGuidejsPsychHelpeR)
