# Ejercicios

## Ejercicio 1

Crea un script en el que hagas lo siguiente:  

  + Cargar librerias necesarias  
  + Importar datos  
  + Preparar datos   
  + Crear gráfica  
  + Crear tabla  

Tendras que mostrar como corre el script con una sesion limpia de RStudio (CONTROL + SHIFT + F10)


#### Notas {.ejercicio -}

(importar datos): Los datos deberían ser, idealmente, de un proyecto en el que estés trabajando. Si no tienes datos disponibles, puedes encontrar bases de datos abiertas de varias maneras:

- Tidytuesday: https://github.com/rfordatascience/tidytuesday
- Buscando en google scholar papers que comparten sus datos: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=data+available+%22osf.io%22+psychology&btnG=
- Buscando directamente en Open Science Foundation: https://osf.io/

(preparación de datos): Algunos ejemplos de preparación de datos: renombrar variables, filtrar, computar nuevas variables, combinar bases...

(gráfica): Algunos ejemplos de gráficas: distribución de variable/s, relación entre variables, ...

(tabla): Algunos ejemplos de tablas: promedios por condición, media, mediana, max y min para algunas variables claves...



## Ejercicio 2

Diseña un **sencillo** experimento:

  + Debes usar algunas de las escalas/tareas que aparecen en: https://github.com/gorkang/jsPsychMaker (ver carpeta canonical_protocol, archivo canonical_protocol_details.csv)
  + Además, debes diseñar una nueva tarea **muy sencilla** o adaptar una nueva escala
  + La duración total del "experimento" no deberia superar los 5 minutos
  
  Tendrás que hacer una breve presentación contándonos el diseño experimental.  

#### Notas {.ejercicio -}

(tareas jsPsychMaker): Usa un máximo de 2 tareas  
(tarea nueva): Puedes diseñar una tarea con una sola pregunta para dos condiciones experimentales, o adaptar un cuestionario breve ya existente (que no tengamos en jsPsychMaker). 





## Ejercicio FINAL

Simularemos datos para tu experimento con jsPsychMonkeys. A continuación:

- Crearemos un proyecto de jsPsychHelper
- Procesaremos los datos
- Crearemos un reporte en Rmd donde incluiremos: 
  + Tabla/s con descriptivos
  + Gráfico/s con resultado

El proyecto tiene que correr en cualquier computador.  


#### Notas {.ejercicio -}

(simulacion datos): El profesor os ayudara con esto y/o os compartira los datos  
(procesamiento datos): Ver [el manual de jsPsychR](https://gorkang.github.io/jsPsychR-manual/QuickGuide.html#QuickGuidejsPsychHelpeR)  
