if (!require('dplyr')) install.packages('dplyr'); library('dplyr')
if (!require("DT")) install.packages("DT"); library("DT")
if (!require("janitor")) install.packages("janitor"); library("janitor")
if (!require('readr')) install.packages('readr'); library('readr')
if (!require("readxl")) install.packages("readxl"); library("readxl")
if (!require("haven")) install.packages("haven"); library("haven")
if (!require("here")) install.packages("here"); library("here")
if (!require("purrr")) install.packages("purrr"); library("purrr")
if (!require("readODS")) install.packages("readODS"); library("readODS")
if (!require("tidyr")) install.packages("tidyr"); library("tidyr")
if (!require("writexl")) install.packages("writexl"); library("writexl")
if (!require('caret')) install.packages('caret'); library('caret')

if (!require('regexplain')) remotes::install_github("gadenbuie/regexplain"); library('regexplain')
if (!require('FFTrees')) remotes::install_github("ndphillips/FFTrees"); library('FFTrees')
