# Introducción {-}

El objetivo de este seminario es aprender a usar [R](https://www.r-project.org/) para preparar y visualizar datos, además de generar reportes reproducibles. Está pensado para alumnos de postgrado con conocimientos básicos de programación.  

También conoceremos [jsPsychR](https://gorkang.github.io/jsPsychRmanual/index.html), un conjunto de herramientas creado por miembros del [CSCN](https://cscn.uai.cl/) para ayudar a crear paradigmas experimentales con [jsPsych](https://www.jspsych.org/), simular participantes, y estandarizar el proceso de preparación y análisis de datos.  

[R](https://www.r-project.org/) es un lenguaje de programación abierto, con una gran comunidad, orientado al trabajo, visualización y modelado de datos en contextos científicos y técnicos. Nos introduciremos de manera práctica a R, resolviendo problemas que encontramos habitualmente durante el quehacer científico, focalizándonos en el trabajo abierto, colaborativo y reproducible.  


## Objetivos {-}

Dar las herramientas básicas a los alumnos para que puedan trabajar de manera autónoma con R y RStudio para el proceso de importación, transformación, visualización y reporte de datos. 

Al finalizar el curso deberíamos ser capaces de:  

* Importar archivos de datos, transformar los datos, crear nuevas variables.
* Realizar análisis de datos exploratorios, visualizar distribuciones y comparar grupos.
* Generar reportes reproducibles con Quarto/RMarkdown
* Crear paradigmas experimentales y un pipeline completo para la preparación de datos con [jsPsychR](https://gorkang.github.io/jsPsychRmanual/index.html).  


## Como empezar {-}

Si ya has completado los pasos [A-B-C](#empezando-en-a-b-c) y [otras dependencias a instalar](#otras-dependencias-a-instalar) indicados en **[preparando nuestro sistema](#preparando-sistema)**, puedes lanzar el siguiente código en tu ordenador para descargar los materiales del curso:  

```{r como-empezar, eval=FALSE}

if (!require('usethis')) install.packages('usethis'); library('usethis')
usethis::use_course("gorkang/R_preparacion_visualizacion_datos")

```

Sigue las instrucciones que aparecen en la Consola para tener un **nuevo proyecto de RStudio con todos los materiales del curso**. El código anterior creará una carpeta llamada `R_preparacion_visualizacion_datos-master`.  

La carpeta `R_preparacion_visualizacion_datos-master` contiene varias cosas. Las mas importantes son:  

- `R_preparacion_visualizacion_datos.Rproj`: para abrir el proyecto de RStudio del curso. **Ábrelo siempre usando este archivo**.  

- Carpeta `docs`: puedes abrir `docs/index.html` en tu navegador para ver el "libro" de este curso. Alternativamente, puedes consultar una [version online del libro](https://gorkang.github.io/R_preparacion_visualizacion_datos/index.html)  

- Carpeta `qmd`: En esa carpeta esta el código fuente de los capítulos del libro   

- Carpeta `data`: Cuando usemos archivos de datos, vendrán de aquí  



::: {.callout-tip collapse="true"}

### En ocasiones encontraras un recuadro como este. En la [versión online del libro](https://gorkang.github.io/R_preparacion_visualizacion_datos/), si haces click sobre el, aparecerá una pista sobre como resolver el ejercicio.  

¡No hagas click sin antes haber intentado resolver el ejercicio sin ayuda!

:::


## Sobre el uso de LLMs (ChatGPT, Gemini, and friends) {LLMs}

Recomiendo **no utilizar** ChatGPT y otros modelos de lenguaje (LLMs) en esta clase. En su defecto, **recomiendo usarlos solo como último recurso**, después de haber intentado resolver los ejercicios, comentado con las compañeras/os, etc. El proceso de aprender a programar requiere construir modelos sobre como funcionan las cosas. Si externalizamos esa construcción a un LLM, nuestra comprensión será mucho más superficial.  

Los LLMs pueden ser útiles para realizar tareas semi-automáticas, o cuando uno ya tiene conocimiento experto, y es capaz de comprender y revisar el output. Pero usarlos para aprender puede interferir en procesos que son esenciales para el aprendizaje. Esto se puede ver, especialmente, en estudiantes con dificultades [Prather et al. 2024](https://doi.org/10.1145/3632620.3671116).  

Para más detalles os sugiero que leáis a Andrew Heiss y su  [política de uso de LLMs](https://compaf24.classes.andrewheiss.com/syllabus.html#ai-large-language-models-and-bullshit). O este artículo: [ChatGPT is bullshit](https://link.springer.com/article/10.1007/s10676-024-09775-5)

<!-- https://doi.org/10.3390/app14104115 -->
<!-- RQ1: The analysis directly answered the primary question concerning the overall impact of LLM usage on programming education outcomes. We identified a significant negative correlation between the average use of LLMs and students’ final grades (Spear-man’s rho = −0.347, p = 0.026), clearly suggesting that an increased general reliance on LLMs correlates with diminished academic performance in programming assignments. -->



---  


## Bibliografía {.bibliografia -}

Bryan, J., & Hester, J. What They Forgot to Teach You About R. https://whattheyforgot.org/  

Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data. O'Reilly Media, Inc. https://r4ds.had.co.nz/  

Wickham, H. (2014). Advanced r. Chapman and Hall/CRC. https://adv-r.hadley.nz/

Xie, Y., Allaire, J. J., & Grolemund, G. (2018). R Markdown: The Definitive Guide. CRC Press. https://bookdown.org/yihui/rmarkdown/  

Yihui Xie (2018). bookdown: Authoring Books and Technical Documents with R Markdown https://bookdown.org/yihui/bookdown/markdown-syntax.html  
