---
title: "La vida nocturna del berberecho salvaje"
author: "Gorka Navarrete"
date: "`r Sys.Date()`"
output: pdf_document
bibliography: IMPORTED.bib  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringi)
library(haven)
library(dplyr)
library(gtsummary)


# Read and prepare DF
DF = haven::read_sav(here::here("data/files/Dafina/Cancer screening risk literacy R1.sav")) |>
  select(IDparticipante, gender, Edad, Sexo, effective, demand, screenbeliefs, numeracy, sciliteracy, statsed, benefits, harms, recommendation, resident, compR1)


```

## Abstract

```{r abstract, echo=FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(n_paragraphs = 1))
```

The truth is not as simple [@gelman2012joroee]. But see also [@brase2021pbr].

## Introducción

```{r introduccion, echo=FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(n_paragraphs = 2))
```

## Materials and Methods

```{r materiales-metodos, echo=FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(n_paragraphs = 1))
```

### Participants


```{r participantes, echo=FALSE, message=FALSE}

DF_table2 = DF |>
  select(effective, demand, screenbeliefs, numeracy, sciliteracy, statsed, benefits, harms, recommendation) |>

  mutate(effective =
           case_when(
             effective == 0 ~ "Inefective",
             effective == 1 ~ "Efective",
             demand == 0 ~ "No demand",
             demand == 1 ~ "Demand"
           )) |>
  mutate(demand =
           case_when(
             effective == 0 ~ "Inefective",
             effective == 1 ~ "Efective",
             demand == 0 ~ "No demand",
             demand == 1 ~ "Demand"
           ))

table1 = DF_table2 |> select(-demand) |>
  gtsummary::tbl_summary(
    by = effective,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} / {N} ({p}%)"
    ),
    type = list(everything() ~ 'continuous'), #Sexo ~ "categorical"),
    missing = "ifany"
  )

table2 = DF_table2 |> select(-effective) |>
  gtsummary::tbl_summary(
    by = demand,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} / {N} ({p}%)"
    ),
    type = list(everything() ~ 'continuous'), #Sexo ~ "categorical"),
    missing = "ifany"
  )


table3 = DF_table2 |> select(-effective, -demand) |>
  gtsummary::tbl_summary(
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{n} / {N} ({p}%)"
    ),
    type = list(everything() ~ 'continuous'), #Sexo ~ "categorical"),
    missing = "ifany"
  )

gtsummary::tbl_merge(tbls = list(table1, table2, table3), tab_spanner = c("By effectivity", "By demand", "Total"))

```

Table 1. Descriptives  


### Materials

```{r materiales, echo=FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(n_paragraphs = 1))
```

## Results

```{r resultados, echo=FALSE, results='asis', message=FALSE}

cat(stringi::stri_rand_lipsum(n_paragraphs = 1))

```

  

### Experiment 1

```{r experimento1, echo=FALSE, message=FALSE}

DF_table4 = DF |> select(effective, demand, gender, resident, statsed, screenbeliefs, compR1, numeracy, sciliteracy, benefits, harms, recommendation)

model1 = lm(recommendation ~ effective + demand + gender + resident + statsed + screenbeliefs + numeracy + sciliteracy + benefits + harms, DF_table4)

gtsummary::tbl_regression(model1, intercept = TRUE) |>
  add_global_p() |>
  bold_labels() |>
  italicize_levels() |>
  add_glance_table(include = c("nobs", "df.residual", "r.squared", "adj.r.squared"))
  
```

Table 2. Results  


## Discussion

```{r discusion, echo=FALSE, results='asis'}
cat(stringi::stri_rand_lipsum(n_paragraphs = 2))
```

## Bibliography
